FROM php:7.1.15-fpm-jessie

WORKDIR /var/www/html

# Workaround for issue where fpm truncates stdout: https://bugs.php.net/bug.php?id=71880
ENV LOG_STREAM="/tmp/stdout"


RUN apt-get update && \
    apt-get install --no-install-recommends -y apt-utils git zip unzip nginx supervisor && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
#    apt-get update && \
#    apt-get install --no-install-recommends -y wget gnupg libicu-dev git zlib1g-dev zip nginx vim nano supervisor alien && \
#    apt-get install -y --no-install-recommends apt-utils && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/* && \
#    docker-php-ext-install zip pdo opcache intl && \
    mkfifo $LOG_STREAM && chmod 777 $LOG_STREAM && \
    # If New Relic is required by your application, use below commands
    #   curl http://repo.ssdm.bskyb.com/newrelic/php_agent/release/newrelic-php5-7.5.0.199-linux.tar.gz | tar xvz && \
    #   NR_INSTALL_SILENT="true", NR_INSTALL_USE_CP_NOT_LN="true" \
    #   newrelic-php5-7.5.0.199-linux/newrelic-install install && \
    #   rm -rf newrelic-php5-7.5.0.199-linux && \
    curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/local/bin --filename=composer && \
#    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
#    apt-get install --no-install-recommends nodejs && \
#    npm install npm@latest -g && \
    composer self-update && \
    composer global require "hirak/prestissimo:^0.3" --no-interaction --no-ansi --quiet --no-progress --prefer-dist && \
    # Nginx logs link to stdout/err
#    ln -sf /dev/stdout /var/log/nginx/access.log && \
#	ln -sf /dev/stderr /var/log/nginx/error.log && \
    mkdir -p /var/www/html/app/cache && \
    chmod 777 /var/www/html/app/cache && \
    composer self-update

# Configure nginx
COPY docker-config/nginx.conf /etc/nginx/nginx.conf
ADD docker-config/nginxErrorPages/ /var/lib/nginx/html

# Configure fpm pool
COPY docker-config/www.conf /usr/local/etc/php-fpm.d/www.conf
#COPY docker-config/apcu.ini /usr/local/etc/php/conf.d/apcu.ini

# Configure supervisord
COPY docker-config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY composer.json composer.lock /var/www/html/
COPY ./web /var/www/html/web
COPY ./src /var/www/html/src
COPY ./app /var/www/html/app

RUN composer install --working-dir=/var/www/html --no-interaction --no-progress

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]