FROM php:7.2.3-fpm-alpine3.7

# Configure nginx
COPY docker-config/nginx.conf /etc/nginx/nginx.conf
#COPY docker-config/nginx.conf /etc/nginx/conf.d/default.conf
ADD docker-config/nginxErrorPages/ /var/lib/nginx/html

# Configure fpm pool
COPY docker-config/www.conf /usr/local/etc/php-fpm.d/www.conf

# Configure supervisord
COPY docker-config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Add application
WORKDIR /var/www/html

# Adding required files and directories
COPY composer.json composer.lock /var/www/html/
COPY ./web /var/www/html/web
COPY ./src /var/www/html/src
COPY ./app /var/www/html/app
#RUN mkdir -p /var/www/html/app/cache && \
#    chmod 777 /var/www/html/app/cache

# Install packages
RUN apk update && \
    apk add curl git nginx supervisor autoconf alpine-sdk && \
#    apk add icu-dev && \
#    pecl install xdebug && \
#    apk add libxml2-dev && \
#    docker-php-ext-install soap && \
#    docker-php-ext-install intl && \
#    pecl install apcu && \
    apk del autoconf alpine-sdk && \
#    pecl clear-cache && \
    mkdir /run/nginx && touch /run/nginx/nginx.pid &&  \
    #rm -r /etc/nginx/conf.d/ && \
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \
    composer self-update && \
    mkdir -p /var/www/html/app/cache && \
    chmod 777 /var/www/html/app/cache && \
    composer install --working-dir=/var/www/html --no-interaction --no-progress

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
